# syntax=docker/dockerfile:1.7
FROM node:20-bookworm-slim

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      build-essential git \
 && rm -rf /var/lib/apt/lists/*

RUN corepack enable \
 && corepack use pnpm@latest-10

WORKDIR /app/web
COPY web/pnpm-lock.yaml web/package.json ./
RUN pnpm install --force

COPY web/ .


EXPOSE 3000
CMD ["pnpm", "run", "dev"]