# syntax=docker/dockerfile:1.7
FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync

COPY ./src ./src
COPY ./resnet/best_model ./resnet/best_model
COPY ./vgg/best_model ./vgg/best_model

ENV PATH="/app/.venv/bin:${PATH}"

WORKDIR /app/src

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
