data:
  train_dir: ./data/train2017
  val_dir: ./data/val2017
  train_captions_dir: ./data/annotations/captions_train2017.json
  val_captions_dir: ./data/annotations/captions_val2017.json
  image_size:
    - 256
    - 256

model:
  name: resnet
  pretrained: True

training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 20

output:
  checkpoint_dir: ./checkpoints/resnet