data:
  train_dir: ./data/train2017
  captions_dir: ./data/annotations/captions_train2017.json
  image_size:
    - 256
    - 256

model:
  name: resnet
  pretrained: True

training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 10