data:
  train_dir: ./data/train2017
  val_dir: ./data/val2017
  train_captions_dir: ./data/annotations/captions_train2017.json
  val_captions_dir: ./data/annotations/captions_val2017.json
  train_cache_path: ./data/train_filtered.json
  val_cache_path: ./data/val_filtered.json
  image_size:
    - 256
    - 256

model:
  name: resnet
  pretrained: True

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 1000
  patience: 10
  min_delta: 0.00001
  subset_percent: 0.1

testing:
  test_dir: ./data/test2017
  subset_percent: 0.05
  predicted_image_dir: ./test/colorised_images
  visualisation: True
  visualisation_dir: ./test/visualisations

output:
  checkpoint_dir: ./resnet/checkpoints
  best_model_dir: ./resnet/best_model