data:
  train_dir: ./data/train2017
  val_dir: ./data/val2017
  train_captions_dir: ./data/annotations/captions_train2017.json
  val_captions_dir: ./data/annotations/captions_val2017.json
  train_cache_path: ./data/train_filtered_vit.json
  val_cache_path: ./data/val_filtered_vit.json
  image_size:
    - 224
    - 224

model:
  name: vit
  pretrained: True

training:
  batch_size: 128
  learning_rate: 0.0005
  num_epochs: 1000
  patience: 5
  min_delta: 0.00001
  subset_percent: 1

testing:
  test_dir: ./data/test2017
  subset_percent: 0.01
  predicted_image_dir: ./test/colorised_images_vit

output:
  checkpoint_dir: ./vit/checkpoints
  best_model_dir: ./vit/best_model